blog/user/models.py
from blog import db
from blog import Serializer
from blog import app

class User(db.Model):
    
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    image_file = db.Column(db.String(20), nullable = False, default = "default.jpg")


    def __init__(self, name=None, email=None, password=None, image_file = None):
        self.name = name
        self.email = email
        self.password = password
        self.image_file = image_file
    
    def get_reset_token(self, expires_sec=1800):
        s = Serializer(app.config["SECRET_KEY"], expires_sec)
        return s.dumps({'user_id': self.id}).decode("utf-8")
    
    @staticmethod
    def verify_reset_token(token):
        s = Serializer(app.config["SECRET_KEY"], expires_in = 1800)
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)
    
    def __repr__(self):
        return f"User('{self.name}','{self.email}')"

blog/user/forms.py
from flask_wtf import FlaskForm
from blog.user.models import User
from wtforms import TextField, PasswordField, BooleanField, TextAreaField, SubmitField
from wtforms.validators import Required, EqualTo, Email


class LoginForm(FlaskForm):
    email = TextField('Email Address', [Required(), Email()])
    password = PasswordField("Password", [Required()])


class RegisterForm(FlaskForm):
    name = TextField("Name", [Required()])
    email = TextField("Email Address", [Required(), Email()])
    password = PasswordField('Password', [Required()])

    confirm = PasswordField("Repeat Password", [
        Required(),
        EqualTo('password', message="Password must match!!")
    ])

    acceept_policy = BooleanField('I accept Policy', [Required()])

class ArticleForm(FlaskForm):
    title = TextField("Title", [Required()])
    content = TextAreaField("Content", [Required()])



class RequestResetForm(FlaskForm):
    email = TextField("Email Address", [Required(), Email()])
    submit = SubmitField("Request Password Reset" )

    def validate_email(self, email):
        user = User.query.filter_by(email = email.data).first()
        if user is None:
            raise ValidationError("There is no account.")

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', [Required()])

    confirm_password = PasswordField("Repeat Password", [
        Required(),
        EqualTo('password', message="Password must match")
    ])

    submit = SubmitField("Reset Password")

blog/article/views.py
from flask import Blueprint, render_template, flash, redirect, url_for,g,session, request
from blog import db, mail
from blog.article.models import Article, Comment
from blog.user.decorators import login_required
from blog.user.models import User

article = Blueprint('articles', __name__, url_prefix='/')


@article.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session["user_id"])

@article.route("/")
def index():
    return render_template("blog/index.html")

@article.route("/about")
def about():
    return render_template("blog/about.html")

@article.route("/articles")
@login_required
def articles():
    articlesAll = Article.query.all()
    return render_template("blog/articles.html", articlesAll = articlesAll)

@article.route('/logout')
@login_required
def logout():
    session.clear()
    flash("Successfully Logout", "warning")
    return redirect(url_for('users.login'))

@article.route('/article/<string:id>', methods=["GET","POST"])
@login_required
def articleFirst(id):
    articleFirst = Article.query.filter_by(id = id).first()
    comments = Comment.query.filter_by(article_id=id).all()
    if request.method == "POST":
        name = request.form.get('name')
        email = request.form.get('email')
        message = request.form.get('message')
        comment = Comment(name=name, email=email, message=message, article_id = id)
        db.session.add(comment)
        flash("Thank you for your coment", "success")
        db.session.commit()
        return redirect(request.url)
    return render_template('blog/article.html', articleFirst = articleFirst, comments = comments)

blog/user/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_mail import Message
from blog import db, mail
from blog.article.models import Article
from blog.user.forms import LoginForm, RegisterForm, ArticleForm, RequestResetForm, ResetPasswordForm
from blog.user.models import User
from blog.user.decorators import login_required, login_management

users = Blueprint('users', __name__, url_prefix='/users')



@users.route("/profile")
@login_required
def profile():
    articles = Article.query.filter_by(author = session['user_name']).all()
    return render_template("user/profile.html", user = g.user, articles = articles)

@users.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session["user_id"])

@users.route("/login", methods=["GET","POST"])
@login_management
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id
            session['user_name'] = user.name
            session['user_email'] = user.email
            flash('welcome %s' % user.name, "primary")
            return redirect(url_for('users.profile'))
        flash("wrong username or password", 'danger')
    return render_template('user/login.html', form = form)

@users.route('/register', methods=["GET","POST"])
@login_management
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(name=form.name.data, email=form.email.data, password=generate_password_hash(form.password.data))
        db.session.add(user)
        db.session.commit()
        session['user_id'] = user.id
        session['user_name'] = user.name
        session['user_email'] = user.email
        flash("Thanks for registering", "success")
        return redirect(url_for('users.profile'))
    return render_template("user/register.html", form = form)

@users.route('/logout')
@login_required
def logout():
    session.clear()
    flash("Successfully Logout", "warning")
    return redirect(url_for('users.login'))

@users.route("/addarticle", methods=["POST","GET"])
@login_required
def addarticle():
    form = ArticleForm(request.form)
    if request.method == "POST":
        title = request.form.get('title')
        author = session['user_name']
        content = request.form.get('content')
        newArticle = Article(title=title, author=author, content=content)
        db.session.add(newArticle)
        db.session.commit()
        flash("Teşekkürler %s" % session['user_name'], "primary")
        return redirect(url_for("users.profile"))
    return render_template("user/addarticle.html", form = form)

@users.route("/edit/<string:id>", methods=["POST","GET"])
@login_required
def edit(id):
    articleId = Article.query.filter_by(id = id).first()
    if request.method == "GET":
        form = ArticleForm()
        form.title.data = articleId.title
        form.content.data = articleId.content
        return render_template("user/edit.html", form = form)
    elif request.method == "POST":
        form = ArticleForm(request.form)
        articleId.title = form.title.data
        articleId.content = form.content.data
        db.session.commit()
        flash("Article updated successfully", "warning")
        return redirect(url_for("users.profile"))

@users.route("/delete/<string:id>")
@login_required
def delete(id):
    articleId = Article.query.filter_by(id = id).first()
    db.session.delete(articleId)
    db.session.commit()
    flash("Article deleted successfully", "secondary")
    return redirect(url_for("users.profile"))

def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message("Password reset request", sender='noreply@info.com', recipients=[user.email])
    msg.body = f"To reset your password visit following link: {url_for('users.reset_token', token = token, _external=True)}"
    mail.send(msg)

@users.route("/reset_password", methods = ["GET","POST"])
def reset_request():
    if "user_id" in session:
        return redirect(url_for("articles.index"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Email has been sent", 'info')
        return redirect(url_for("users.login"))
    return render_template("user/reset_request.html", form = form)

@users.route("/reset_password/<string:token>", methods=["GET","POST"])
def reset_token(token):
    if "user_id" in session:
        return redirect(url_for("articles.index"))
    user = User.verify_reset_token(token=token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pasww = generate_password_hash(form.password.data)
        user.password = hashed_pasww
        db.session.commit()
        flash("Password changed", "success")
        return redirect(url_for('users.login'))
    return render_template("user/reset_token.html", form = form)


@users.route("profile/account", methods = ["GET","POST"])
@login_required
def account():
    user_image = User.query.filter_by(image_file = User.image_file).first()
    image_file = url_for('static', filename='img/profile_pics/'+ user_image.image_file)
    return render_template("user/account.html", image_file = image_file)

    
    
    

blog/templates/user/account.html
{% extends "layout.html" %}

{% block body %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{image_file}}">
            <div class="media-body">
                <h2 class="account-heading">{{session["user_name"]}}</h2>
                <p class="text-secondary">{{session['user_email']}}</p>
            </div>
        </div>
    </div>
{% endblock body %}

blog/templates/user/addarticle.html
{% extends "layout.html" %}


{% block body %}
{% from "helpers/formhelpers.html" import render_field %}
<div class = "container jumbotron">
    <h3> Your Article </h3>
    <h5>Thank you for sharing your knowledge {{session["user_name"]}}</h5>
    <hr>
</div>
<div class = "container">
<form method="POST">
    {{ render_field(form.title, class="form-control") }}
    {{ render_field(form.content, class="form-control") }}
    <button type="submit" class="btn btn-primary">Add Article</button>
</form>
</div>
{% endblock body %}

blog/templates/user/edit.html
{% extends "layout.html" %}


{% block body %}
{% from "helpers/formhelpers.html" import render_field %}
<div class = "container jumbotron">
    <h3> Your Article </h3>
    <h5>Thank you for sharing your knowledge {{session["user_name"]}}</h5>
    <hr>
</div>
<div class = "container">
<form method="POST">
    {{ render_field(form.title, class="form-control") }}
    {{ render_field(form.content, class="form-control") }}
    <button type="submit" class="btn btn-primary">Update Article</button>
</form>
</div>
{% endblock body %}

blog/templates/user/login.html
{% extends "layout.html" %}

{% block body %}
{% from "helpers/formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="row no-gutter">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-xl-7 mx-auto">
                            <h3 class="display-4">Login!</h3>
                            <p class="text-muted mb-4">Enter Email and Password!</p>
                            <form method="POST">
                                {{ form.csrf_token }}
                                <div class="form-group mb-3">
                                    {{ render_field(form.email, class="form-control rounded-pill border-0 shadow-sm px-4") }}
                                </div>
                                <div class="form-group mb-3">
                                    {{ render_field(form.password, class="form-control rounded-pill border-0 shadow-sm px-4") }}
                                </div>
                                <button type="submit" value="Login" class="btn btn-dark btn-block text-uppercase mb-2 rounded-pill shadow-sm">Login!</button>
                                <div class="text-center d-flex justify-content-between mt-4">
                            </form>
                            <a href= "{{url_for('users.register')}}" class="btn btn-info btn-block text-uppercase mb-2 rounded-pill shadow-sm"> Register and join us! </a>
                            <hr>
                            <a href= "{{url_for('users.reset_request')}}" class="btn btn-info btn-block text-uppercase mb-2 rounded-pill shadow-sm"> Forgot Password ? </a>
                        </div>
                    </div>
                </div><!-- End -->
            </div>
        </div><!-- End -->
    </div>
</div>
{% endblock body %}

blog/templates/user/profile.html
{% extends "layout.html" %}

{% block body %}
<div class="container jumbotron" style="background-color: steelblue;">
    <h3> Your Article </h3>
    <hr>
    <p>Thank you for sharing your knowledge {{session["user_name"]}}</p>
</div>

<div class="container">
    <a href="{{url_for('users.addarticle')}}" class="btn btn-success">Add Article</a>
    <a href="{{url_for('users.account')}}" class="btn btn-success">My Account</a>
    <hr>
    
    {% if articles %}
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Date</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for art in articles %}
            <tr>
                <td><a href="{{url_for('articles.articleFirst', id = art.id)}}" class="btn btn-dark">{{art.title}}</a></td>
                <td>{{art.author}}</td>
                <td>{{art.created_date}}</td>
                <td><a href="{{url_for('users.edit', id = art.id)}}" class="btn btn-warning">Update</a></td>
                <td><a href="{{url_for('users.delete', id = art.id)}}" class="btn btn-danger">Delete</a></td>
            </tr>

            {% endfor %}
        </tbody>
    </table>

    {% else %}
    <div>There is no article!</div>
    {% endif %}

</div>
{% endblock body %}

blog/templates/user/register.html
{% extends "layout.html" %}


{% block body %}
{% from "helpers/formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-xl-7 mx-auto">
                    <h3 class="display-4">Register!</h3>
                    <p class="text-muted mb-4">Please fill in the required places!</p>
                    <form method="POST">
                        {{ form.csrf_token }}
                        {{render_field(form.name, class="form-control rounded-pill border-0 shadow-sm px-4")}}

                        {{render_field(form.email, class="form-control rounded-pill border-0 shadow-sm px-4")}}

                        {{render_field(form.password, class="form-control rounded-pill border-0 shadow-sm px-4")}}

                        {{render_field(form.confirm, class="form-control rounded-pill border-0 shadow-sm px-4")}}

                        {{ render_field(form.acceept_policy, class="input checkbox") }}

                        <button type="submit" value='Register' class="btn btn-dark btn-block text-uppercase mb-4 rounded-pill shadow-sm">
                            Register!</button>
                    </form>
                    <a href="{{url_for('users.login')}}" class="btn btn-dark btn-block text-uppercase mb-2 rounded-pill shadow-sm"> Login! </a>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock body %}

blog/templates/user/reset_request.html
{% extends "layout.html" %}

{% block body %}
{% from "helpers/formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="row no-gutter">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-xl-7 mx-auto">
                            <h3 class="display-4">Reset Password!</h3>
                            <p class="text-muted mb-4">Enter Email!</p>
                            <form method="POST">
                                {{ form.csrf_token }}
                                <div class="form-group mb-3">
                                    {{ render_field(form.email, class="form-control rounded-pill border-0 shadow-sm px-4") }}
                                </div>
                                {{render_field(form.submit, class="btn btn-dark btn-block text-uppercase mb-2 rounded-pill shadow-sm")}}
                                
                                <div class="text-center d-flex justify-content-between mt-4">
                            </form>
                        </div>
                    </div>
                </div><!-- End -->
            </div>
        </div><!-- End -->
    </div>
</div>
{% endblock body %}

blog/templates/user/reset_token.html
{% extends "layout.html" %}

{% block body %}
{% from "helpers/formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="row no-gutter">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-xl-7 mx-auto">
                            <h3 class="display-4">Reset Password!</h3>
                            <p class="text-muted mb-4">Enter password!</p>
                            <form method="POST">
                                {{ form.csrf_token }}
                                <div class="form-group mb-3">
                                    {{ render_field(form.password, class="form-control rounded-pill border-0 shadow-sm px-4") }}
                                </div>
                                 <div class="form-group mb-3">
                                    {{ render_field(form.confirm_password, class="form-control rounded-pill border-0 shadow-sm px-4") }}
                                </div>
                                {{render_field(form.submit, class="btn btn-dark btn-block text-uppercase mb-2 rounded-pill shadow-sm")}}
                                
                                <div class="text-center d-flex justify-content-between mt-4">
                            </form>
                        </div>
                    </div>
                </div><!-- End -->
            </div>
        </div><!-- End -->
    </div>
</div>
{% endblock body %}